//This file is automatically generated, modifications will be lost!
#include <CommonGameKit/CommonGameKit.h>

#include "ProjectExpressions.h"

void CCExpressionSetup(void)
{
    CCExpressionEvaluatorRegister(CC_STRING("game"), CCProjectExpressionGame);
}
