//This file is automatically generated, modifications will be lost!
#include <CommonGameKit/CommonGameKit.h>

#include "ProjectExpressions.h"

void B2ExpressionSetup(void)
{
    CCExpressionEvaluatorRegister(CC_STRING("game"), B2ProjectExpressionGame);
}
