//This file is automatically generated, modifications will be lost!
#define CC_QUICK_COMPILE
#include <CommonGameKit/CommonGameKit.h>

#include "ProjectExpressions.h"

void B2ExpressionSetup(void)
{
    CCExpressionEvaluatorRegister(CC_STRING("game"), B2ProjectExpressionGame);
    CCExpressionEvaluatorRegister(CC_STRING("app-data-dir"), B2ProjectExpressionAppDataDir);
}
